### ISSUE TITLE
Support veewee/xml 3.x

### ISSUE THREAD

**Issue by sprankhub** [php-soap/psr18-wsse-middleware#16]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

This library should add support for `veewee/xml` version 3.x.

Thanks!

**Comment by veewee** [comment]
I'dd surely accept a PR for that. ;) Care to give it a spin?

**Comment by sprankhub** [comment]
Here you go ;-) Mind that I couldn't test this on a real-world example, though.

**Comment by veewee** [comment]
Thanks!
v3 was mostly a breaking upgrade for the reader component. It will work the same for this package as v2.
